version: '1.0'

services:
    influxdb:
        image: kaphagel/influxdb:1.8
        container_name: ${CONTAINER_PREFIX}_influxdb
        ports:
            - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
        volumes:
            - /var/lib/promobas/influxdb:/var/lib/influxdb
        restart: always
        networks:
            - backend
            - frontend
networks:
    backend:
    frontend:
